= Module One

This is version *{page-component-display-version}* of Module One in Component B.

== Page source

This page is sourced from [.path]_demo-component-b/docs/modules/module-one/pages/overview.adoc_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in Module One*, the xref syntax would be `\xref:overview.adoc[]`.

To create a cross reference *to this page from a page in the ROOT module of Component B*, the xref syntax would be `\xref:module-one:overview.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in Component A*, the xref syntax would be `\xref:component-b:module-one:overview.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in Component A*, the xref syntax would be `\xref:1.0@component-b:module-one:overview.adoc[]`.

== Table

[cols="2,^1,^1,^1,^1,^1,^1,^2"]
|===
|Language |HTML export tool |HTML import tool |Tables |Link titles |`class` attribute |`id` attribute |Release date

|https://en.wikipedia.org/wiki/Markdown[Markdown]	
|Yes	
|No	
|?	
|auto	
|Yes/No	
|Yes	
|2004-03-19

|https://en.wikipedia.org/wiki/WhatsApp[WhatsApp]	
|No	
|Yes/No	
|Yes
|No	
|?	
|auto	
|2016-03-16
|===

== Table 2

++++
<style>
td.tableblock .bg-yellow p {
    background-color: yellow;
}
</style>
++++

[cols="^1a,^4a,^1a,^4a,^1a,^2a,^1a,^1a,^1a"]
|===
|[.bg-yellow]#11#

|872349ae

|11

|TxID

|10

|4002

|0f

|04

|14!

|===
